import './globals.css'
import Footer from "@/components/Footer";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}) {
    return (
        <html lang="cs">
        <head>
            <title>Microagency</title>
        </head>
        <body className="antialiased bg-black text-white text-base font-sans flex flex-col min-h-screen">
        <main className="bg-black flex-1 leading-[1.3]">
            {children}
        </main>
        <Footer/>
        </body>
        </html>
    )
}
